// <auto-generated />
namespace WebBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_table_NV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_table_NV));
        
        string IMigrationMetadata.Id
        {
            get { return "202012151046390_edit_table_NV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
