// <auto-generated />
namespace WebBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetablekhachhang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetablekhachhang));
        
        string IMigrationMetadata.Id
        {
            get { return "202011201411002_update-table-khachhang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
